name: Deploy web app
description: Deploy the web app to Azure

inputs:
  web_app_location:
    required: true
    description: 'The location of the web app'
  web_app_artifact_location:
    required: true
    description: 'The location of the web app artifact, relative to the web app location'
  client_id:
    description: 'The client id of the federated user'
    required: true
  tenant_id:
    description: 'The tenant id of the federated user'
    required: true
  subscription_id:
    description: 'The subscription to deploy to'
    required: true
  github_token:
      description: 'The token to use to login to GitHub'
      required: true
  deployment_token:
      description: 'The token to use to deploy the web app'
      required: true
    
runs:
  using: composite  
  steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.client_id }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      - name: Build and Deploy web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ inputs.deployment_token }}
          repo_token: ${{ inputs.github_token }}
          action: "upload"
          app_location: ${{ inputs.web_app_location }}
          app_artifact_location: ${{ inputs.web_app_artifact_location }}
